# SPDX-FileCopyrightText: 2026 OpenAdmin
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from typing import Any, Callable, Protocol


class AdminPageProtocol(Protocol):
    def stat(self, name: str, description: str | None = None) -> Callable[..., Any]: ...
    def table(
        self, name: str, description: str | None = None
    ) -> Callable[..., Any]: ...
    def markdown(self, name: str) -> Callable[..., Any]: ...
    def action_get(
        self, name: str, description: str | None = None
    ) -> Callable[..., Any]: ...
    def action_post(
        self, name: str, description: str | None = None
    ) -> Callable[..., Any]: ...
    def action_put(
        self, name: str, description: str | None = None
    ) -> Callable[..., Any]: ...
    def action_patch(
        self, name: str, description: str | None = None
    ) -> Callable[..., Any]: ...
    def action_delete(
        self, name: str, description: str | None = None
    ) -> Callable[..., Any]: ...
    def form_post(
        self, name: str, description: str, hide: bool = False
    ) -> Callable[..., Any]: ...
    def form_put(
        self, name: str, description: str, hide: bool = False
    ) -> Callable[..., Any]: ...
    def form_patch(
        self, name: str, description: str, hide: bool = False
    ) -> Callable[..., Any]: ...
    def form_delete(
        self, name: str, description: str, hide: bool = False
    ) -> Callable[..., Any]: ...
    def area_chart(self, name: str, description: str) -> Callable[..., Any]: ...
    def bar_chart(self, name: str, description: str) -> Callable[..., Any]: ...
    def line_chart(self, name: str, description: str) -> Callable[..., Any]: ...
    def pie_chart(self, name: str, description: str) -> Callable[..., Any]: ...
